### ISSUE TITLE
2023-10-12 Site To-Do Status

### ISSUE THREAD

**Issue by PandoramicView** [PandoramicView/PandoramicView.github.io#2]
- [ ] Shrink header height
- [ ] Move hub RSS into footer
- [ ] Set up RSS home page
- [ ] Embed substack subscribe... somewhere
- [ ] Migrate comments to github
- [ ] Re-format about page hugemongous list
